server:
  port: 80

spring:
  application:
    name: neuro-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/javalab-2023
    username: postgres
    password: marsel55
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      schema: public

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true